college_n_codes = {'E001': 'Acharya Institute of Technology-Soladevanahalli, Bengaluru',
                   'E003': 'A.C.S. College of Engineering-Kambipura Mysore Road, Bengaluru',
                   'E004': 'Adichunchanagiri Institute Of Technology-Jyothi Nagara, Chikkamagaluru',
                   'E005': 'Akash Institute of Engineering and Technology-Devanahalli, Bengaluru Rural',
                   'E006': 'Alvas Institute of Engineering and Technology-Moodbidri, Mangaluru',
                   'E007': 'AMC Engineering College-Bannerghatta Rd, Bengaluru',
                   'E009': 'Angadi Institute of Technology and Management-Savagaon Road, Belagavi',
                   'E011': 'APS College of Engineering-Kanakapura Road, Bengaluru',
                   'E012': 'Atria Institute of Technology-Hebbal, Bengaluru',
                   'E013': 'Akshaya Institute of Technology-Koratagere Road, Tumakuru',
                   'E014': 'Bharatesh Institute of Technology-Shindhollicross, Belagavi',
                   'E015': 'B.N.M. Institute of Technology-Banashankari, Bengaluru',
                   'E016': 'KLE Technological University Formerly known as BVBCET-Vidyanagar, Hubballi',
                   'E017': 'Ballari Institute of Technology And Management-Near Allipura, Ballari',
                   'E018': 'Bangalore College of Engineering and Technology-Chandapura, Bengaluru',
                   'E019': 'Bangalore Institute of Technology-V V Puram, Bengaluru',
                   'E020': 'Bangalore Technological Institute-Chikkanayakanahalli Dinne, Bengaluru',
                   'E021': 'Bapuji Institute of Engineering and Technology-Shamanur Road, Davangere',
                   'E023': 'Basavakalyan Engineering College-NH9 Basavakalyan, Bidar',
                   'E024': 'Basaveshwar Engineering College-Vidya Nagar, Bagalkote',
                   'E026': 'BLDEAs V.P. Dr.P.G.Halakatti College of Engineering and Technology-Ashram Road, Vijayapura',
                   'E027': 'BMS College of Engineering-Basavanagudi, Bengaluru',
                   'E028': 'BMS Institute of Technology and Management-Yelahanka, Bengaluru',
                   'E030': 'Brindavan College of Engineering-Yelahanka, Bengaluru',
                   'E032': 'C.M.R. Institute of Technology-Brookefield, Bengaluru',
                   'E033': 'Cambridge Institute of Technology-K R Puram, Bengaluru',
                   'E035': 'Channabasaveshwara Institute of Technology- Gubbi, Tumakuru',
                   'E036': 'Chanakya University-Devanahalli, Bengaluru Rural',
                   'E037': 'City Engineering College-Doddakalasandra, Bengaluru',
                   'E038': 'Coorg Institute of Technology-Ponnampet, South Kodagu',
                   'E039': 'Dayananda Sagar Academy of Technology and Management-Kanakpura Road, Bengaluru',
                   'E040': 'Dayananda Sagar College of Engineering-Kumaraswamy Layout, Bengaluru',
                   'E041': 'DON BOSCO Institute of Technology-Kumbalgodu, Bengaluru',
                   'E042': 'Dr. Ambedkar Institute of Technology-Malathahalli, Bengaluru',
                   'E043': 'Yenepoya Institute of Technology formerly known as Dr. M V Shetty Institute of Technology\r\nMoodbidri  Mangaluru',
                   'E044': 'Dr.Shri Shri Shivakumara Mahaswamy College of Engineering-Nelamangala, Bengaluru Rural',
                   'E045': 'Dr H N National College Of Engineering-Jayanagar, Bengaluru',
                   'E046': 'East Point College of Engineering and Technology-Avalahalli, Bengaluru',
                   'E048': 'East West Institute of Technology-BEL Layout, Bengaluru',
                   'E049': 'Garden City University-Old Madras Road, Bengaluru',
                   'E050': 'Global Academy of Technology-Rajarajeshwari Nagar, Bengaluru',
                   'E051': 'GM Institute of Technology-P B Road, Davangere',
                   'E053': 'Gopalan College of Engineering And Management-Whitefield, Bengaluru',
                   'E055': 'GSSS Institute of Engineering and Technology for Women-Metagalli, Mysuru',
                   'E056': 'H.K.E.Societys P.D.A. College of Engineering-Aiwan E Shahi area, Kalaburgi',
                   'E058': 'Sri Jayachamarajendra College of Engineering constituent college of JSS Science and Technology\r\nUniversity-Manasagangothri  Mysuru',
                   'E059': 'Jawaharlal Nehru New College of Engineering JNNCE-Swalanga Road, Shivamogga',
                   'E060': 'JSS Academy of Technical Education-Kengeri Main Road, Bengaluru',
                   'E061': 'JSS Science and Technology University-Mysuru',
                   'E062': 'Jain College of Engineering-T.S Nagar, Belagavi',
                   'E063': 'Jnana Vikas Institute of Technology-Bidadi, Ramnagar Taluk, Bengaluru Rural',
                   'E064': 'Jain College of Engineering and Research-Udyambag, Belagavi',
                   'E065': 'KLE Technological University  Formerly called as KLE Dr. M.S. Sheshgiri College of Engineering and\r\nTechnology-Udyambag  Belagavi',
                   'E066': 'KLE College of Engineering and Technology-Chikodi Dist., Belagavi',
                   'E067': 'K.S School of Engineering And Management-Off Kanakapura Road, Bengaluru',
                   'E068': 'K.S. Institute of Technology-Kanakapura Main Road, Bengaluru',
                   'E069': 'KVG College Of Engineering-Sullia, Dakshina Kannada',
                   'E070': 'Kalpataru Institute of Technology-B H Road, Tiptur',
                   'E071': 'Karavali Institute of Technology-Kottara, Mangaluru',
                   'E072': 'K L E  Institute of Technology-Gokul, Hubbali',
                   'E073': 'KLS Gogte Institute of Technology-Udyambag, Belagavi',
                   'E074': 'KLS Vishwanathrao Deshpande Institute of Technology-Dandeli Road, Haliyal',
                   'E075': 'KNS Institute of Technology-Yelahanka, Bengaluru',
                   'E076': 'M.S. Engineering College-Sadahalli, Bengaluru',
                   'E077': 'M.S. Ramaiah Institute of Technology-MSR Nagar, Bengaluru',
                   'E078': 'Maharaja Institute of Technology-Belawadi, Mandya',
                   'E079': 'Malnad College of Engineering-Rangoli Halla, Hassan',
                   'E080': 'Mangalore Institute of Technology and Engineering-Moodbidri, Mangaluru',
                   'E081': 'Moodalakatte Institute of Technology-Moodalakatte, Udupi',
                   'E082': 'Maharaja Institute of Technology-Thandavapura, Mysuru',
                   'E083': 'Mysuru Royal Institute of Technology-Palahallli, Mandya District',
                   'E084': 'Nagarjuna College of Engineering And Technology-Devanahalli, Bengaluru',
                   'E085': 'The National Institute of Engineering North Campus-Koorgalli, Mysuru',
                   'E086': 'Nitte Meenakshi Institute of Technology-Yelahanka, Bengaluru',
                   'E088': 'Navodaya Institute of Technology-Bijangera, Raichur',
                   'E089': 'P.E.S.College of Engineering-PES College Road, Mandya',
                   'E090': 'PES Institute of Technology and Management-Kotegangoor Cost, Shivamogga',
                   'E094': 'Proudhadevaraya Institute of Technology-TB Dam Road, Hosapete',
                   'E095': 'R V College of Engineering-Mysore Road, Bengaluru',
                   'E096': 'R.L. Jalappa Institute of Technology-Kodigehalli, Doddaballapur',
                   'E097': 'R.R. Institute of Technology-Chikkabanavara, Bengaluru',
                   'E098': 'R T E Societys Rural Engineering College-Hulkoti, Gadag',
                   'E099': 'Raja Rajeswari College of Engineering-Kumbalgodu, Bengaluru',
                   'E100': 'Rajeev Institute of Technology-BM Bypass Road, Hassan',
                   'E101': 'Rajiv Gandhi Institute of Technology-R T Nagar Post, Bengaluru',
                   'E102': 'Rao Bahadur Y Mahabaleswarappa Engineering College-Cantonment, Ballari',
                   'E104': 'RNS Institute of Technology-R R Nagar Post, Bengaluru',
                   'E105': 'Bheemanna Khandre Institute of Technology-Bhalki, Bidar',
                   'E107': 'SJB Institute of Technology-Kengeri, Bengaluru',
                   'E108': 'S J C Institute of Technology-BB Road, Chikkaballapur',
                   'E109': 'S.E.A. College of Engineering and Technology-K R Puram, Bengaluru',
                   'E110': 'SSETs S.G. Balekundri Institute of Technology-Shivabasva Nagar, Belagavi',
                   'E112': 'Sahyadri College of Engineering and Management-Adyar, Mangaluru',
                   'E113': 'Sai Vidya Institute of Technology-Rajan Kunte, Bengaluru',
                   'E114': 'Sambhram Institute of Technology-Jalahalli East, Bengaluru',
                   'E116': 'Sapthagiri NPS University-Hesarghatta Main Road, Bengaluru',
                   'E117': 'SDM College of Engineering and Technology, Tulu Minority-Kalaghatagi, Dharwad',
                   'E118': 'SDM Institute of Technology, Tulu Minority-Ujire, Dakshina Kannada',
                   'E119': 'SECAB Institute of Engineering andTechnology-Nauraspur-Bagalkot Road, Vijayapura',
                   'E121': 'Sri Sairam College of Engineering-Anekal, Bengaluru',
                   'E122': 'Shree Devi Institute of Technology-Kenjar, Mangaluru',
                   'E123': 'Shri Madhwa Vadiraja Institute of Technology and Management-Bantakal, Udupi',
                   'E124': 'Shridevi Institute of Engineering and Technology-Sira Road, Tumakuru',
                   'E125': 'Siddaganga Institute of Technology-B H Road, Tumakuru',
                   'E126': 'Sir M.Visvesvaraya Institute of Technology-Yelahanka, Bengaluru',
                   'E127': 'SJM Institute of Technology-NH 4 Bye-pass, Chitradurga',
                   'E128': 'Smt. Kamala and Sri Venkappa M. Agadi College of Engineering and Technology-Laxmeswar,\r\nGadag',
                   'E132': 'Sri Krishna Institute of Technology-Chikkabanavara, Bengaluru',
                   'E136': 'Sri Taralabalu Jagadguru Institute of Technology-Haveri Dist., Ranebennur',
                   'E137': 'Sri Venkateshwara College of Engineering-KIAL Road, Bengaluru',
                   'E138': 'Srinivas Institute of Technology-Hampankatta, Mangaluru',
                   'E141': 'T. John Institute of Technology-Bannerghatta Road, Bengaluru',
                   'E142': 'The National Institute of Engineering South Campus-Mananthavady Road, Mysuru',
                   'E143': 'Tontadarya College of Engineering-Mundaragi Road , Gadag',
                   'E144': 'Veerappa Nisty Engineering College-Shorapur, Yadgir',
                   'E145': 'Vemana Institute of Technology-Koramangala, Bengaluru',
                   'E146': 'Vidya Vikas Institute of Engineering and Technology-Alnahally, Mysuru',
                   'E147': 'Vidyavardhaka College of Engineering-Gokulam, Mysuru',
                   'E148': 'Vivekananda College of Engineering and Technology-Puttur, Dakshin Kannada',
                   'E149': 'Vivekananda Institute of Technology-Kengeri, Bengaluru',
                   'E152': 'ATME College of Engineering-Bannur Road, Mysuru',
                   'E156': 'Jyothy Institute of Technology-Tathguni, Bengaluru',
                   'E158': 'Shetty Institute of Technology - Gulbarga Shahabad Road, Kalaburagi',
                   'E159': 'Lingaraj Appa Engineering-Gornalli, Bidar',
                   'E161': 'Cambridge Institute of Technology North Campus-Kundana, Bengaluru',
                   'E164': 'Reva University-Yelahanka, Bengaluru',
                   'E165': 'Alliance College of Engineering and Design. Alliance University-Anekal, Bengaluru',
                   'E171': 'GITAM Deemed to be University-Dodaballapur taluk, Bengaluru',
                   'E172': 'Mysore College of Engineering and Management-Chikkahalli, Mysuru',
                   'E173': 'Presidency University-Yelahanka, Bengaluru',
                   'E183': 'Jain Institute of Technology-Avaragere Village, Davangere',
                   'E186': 'Nitte School of Architecture Planning and Design-Yelahanka, Bengaluru',
                   'E187': 'CMR University-Bagalur-Chagalatti, Bengaluru',
                   'E194': 'Jain College of Engineering and Technology-Unkal, Hubballi',
                   'E195': 'Navkis College of Engineering -Kandali NH75, Hassan',
                   'E197': 'M.S. Ramaiah University of Applied Sciences-MSR Nagar, Bengaluru',
                   'E198': 'R V Institute of Technology and Management-J P Nagar, Bengaluru',
                   'E199': 'Biluru Gurubasava Mahaswamiji Institute of Technology-Mudhol, Bagalkot',
                   'E201': 'G Madegowda Institute of Technology-Maddur, Mandya District',
                   'E202': 'C Byregowda Insitute of Technology-Thoradevandahalli, Kolar',
                   'E203': 'Amruta Institute of Engineering and Management Science-Bidadi, Ramnagar Taluk, Bengaluru\r\nRural',
                   'E204': 'H.K.E. Societys Sir M. Visvesvaraya College of Engineering-Yermarus Camp, Raichur',
                   'E205': 'Vijaya Vittala Institution of Technology-Kothanur, Bengaluru',
                   'E206': 'Cauvery Institute Of Technology-Sundahalli, Mandya',
                   'E207': 'BGS College of Engineering and Technology-Mahalaxmipuram, Bengaluru',
                   'E208': 'A.G.M Rural College of Engineering and Technology-Varur, Hubballi',
                   'E209': 'Aditya College of Engineering and Technology-Yelahanka, Bengaluru',
                   'E210': 'Impact College Of Engineering and Applied Science-Sahakar Nagar, Bengaluru',
                   'E211': 'East West College of Engineering-Yelahanka, Bengaluru',
                   'E212': 'Seshadripuram Institute of Technology - Jaipura Hobli, Mysuru'}